include(":app_category")
include(":app_track")
include(":lib_weight")
include(":lib_base")
include(":lib_utils")
include(":lib_adapter")
include(":common")
include(":common_service")
include(":app_login")
include(":app_main")
include(":app_home")
include(":app_message")
include(":app_mine")
include(":app")
rootProject.name = "Chaos"