rootProject.name = "Chaos"
include(":lib_base")
include(":lib_utils")
include(":common")
include(":common_service")
include(":app_login")
include(":app_main")
include(":app_home")
include(":app_active")
include(":app_message")
include(":app_mine")
include(":app")